---
cert_options_defaults:
    service:
        name: "{{ service.name }}"
        user: "{{ service.user }}"
    key:
        mode: a=,g=rw,u=rw
    csr:
        subject_alt_names: []
    crt:
        not_after: +90d
        not_before: -1d
        mode: a=,g=rw,u=rw
